### ISSUE TITLE
Stripping out ROS, question...

### ISSUE THREAD

**Issue by antithing** [SmartRoboticSystems/aruco_mapping#6]
Hi, thank you for making this available. i am attempting to strip out the ROS dependencies, and am close, but missing something...

My code builds, and runs, but I cannot get the global marker poses to look right. I think I am missing something around here:

https://github.com/SmartRoboticSystems/aruco_mapping/blob/master/src/aruco_mapping.cpp#L497

Can you explain what this is doing please?

```
    listener_->lookupTransform("world",marker_tf_name.str(),ros::Time(0),
                                   markers_[index].tf_to_world);
```

What would the non-ROS equivalent of this section be? Or, how can i get the world position of each marker from the position in camera-space? 

Thanks again!

**Comment by vannem95** [comment]
Were you able to get it to work without ros?

**Comment by antithing** [comment]
Nope, i ended up writing my own application in the end. Good luck!

**Comment by vannem95** [comment]
is it private? if not, do you mind sharing it with me?

**Comment by antithing** [comment]
Sorry, its private code. I can tell you that I took a different approach, using bundle adjustment with Ceres to  refine the poses and tag corner locations. Good luck!
